Min240923
playwrightvn/pw-discovery pull request #100
Opened 2024-09-30 02:22 UTC by minvp

Hiện tại em đang thấy khi em open url https://demoqa.com/Account/v1/User thì trang trắng nên khi run script thì sẽ bị error 400. Anh check giúp em với ạ.

2024-10-01 09:38 UTC, minhphong306 commented on daily-challenges/2024-09/23/min240923.spec.ts
> +const { test, expect } = require('@playwright/test');
Sử dụng import cho đồng bộ

2024-10-01 09:40 UTC, minhphong306 commented on daily-challenges/2024-09/23/min240923.spec.ts
> +        username: 'playwright',
Chú ý tên field theo API doc
```suggestion
        userName: 'playwright',
```

2024-10-01 09:40 UTC, minhphong306 requested changes
Please fix comments

2024-10-01 12:21 UTC, minvp commented on daily-challenges/2024-09/23/min240923.spec.ts
> +const { test, expect } = require('@playwright/test');
updated

2024-10-01 12:21 UTC, minvp commented on daily-challenges/2024-09/23/min240923.spec.ts
> +        username: 'playwright',
updated

2024-10-04 01:10 UTC, minhphong306 commented
Sorry, I have been busy for two days.

2024-10-04 01:12 UTC, minhphong306 approved these changes
Looks good to me

2024-10-04 01:12 UTC, merged