Min240926
playwrightvn/pw-discovery pull request #103
Opened 2024-09-30 08:35 UTC by minvp

2024-10-01 06:33 UTC, minhphong306 commented on daily-challenges/2024-09/21/min240921.spect.ts
Rename file

2024-10-01 06:34 UTC, minhphong306 requested changes
Please fix my comments.

2024-10-01 12:32 UTC, minvp commented on daily-challenges/2024-09/21/min240921.spect.ts
updated

2024-10-04 01:16 UTC, minhphong306 approved these changes
Looks good to me

2024-10-04 01:16 UTC, merged