lcaloi_29 add solution 17-09-2024
playwrightvn/pw-discovery pull request #114
Opened 2024-10-02 08:38 UTC by LCALoi123

2024-10-02 16:22 UTC, minhphong306 commented on daily-challenges/2024-09/17/lcaloi_29.spec.ts
> +        if (await item_info.nth(0).innerText() === prodInfo.name) {
Không dùng lộn xộn camelCase và snake_case

2024-10-02 16:22 UTC, minhphong306 requested changes
Please fix comments

2024-10-04 01:26 UTC, minhphong306 commented on daily-challenges/2024-09/17/lcaloi_29.spec.ts
> +    if (number > 2 && number % 2 === 0 || number <= 1) {
Mặc dù không sai, nhưng hãy thêm ngoặc vào nhé bro.
Viết code làm sao để đồng đội không phải hỏi câu nào, hoặc ko phải confuse.
```suggestion
    if ((number > 2 && number % 2 === 0) || number <= 1) {
```

2024-10-04 01:27 UTC, minhphong306 requested changes
Please fix comments

2024-10-04 02:08 UTC, LCALoi123 commented
em đã fix comments, anh recheck lại giúp em nha. cám ơn anh

2024-10-05 14:02 UTC, minhphong306 approved these changes
Looks good to me

2024-10-05 14:02 UTC, merged