Solution 18 09 2024
playwrightvn/pw-discovery pull request #115
Opened 2024-10-02 08:41 UTC by LCALoi123

2024-10-04 01:19 UTC, minhphong306 commented on daily-challenges/2024-09/17/lcaloi_29.spec.ts
> +    expect(Number((await page.locator('td.total-price').innerText()).replace('$', 'totalPrice')));
Theo anh ko nên viết tắt quá ntn. KHó debug.
Đối với các value cần await, em nên tách ra để debug dễ hơn.
VD:
const val = await ....
// do smth with val

2024-10-04 01:20 UTC, minhphong306 commented on daily-challenges/2024-09/18/lcaloi_29.spec.ts
> +function calculateAge(input: number) {
Thêm 1 dòng trống iữa import và phần còn lại để dễ đọc, dễ nhìn hơn.

2024-10-04 01:22 UTC, minhphong306 requested changes
Please fix comments.

Có cảm giác code của em run được nhưng khó maintain vì structure khó nhìn. Hơi "junior" chút.

- Có dòng trống giữa các code block.
- Đặt tên biến đồng bộ, tránh camelCase, snake_case lẫn lộn

2024-10-04 02:19 UTC, LCALoi123 commented
> Please fix comments.
> 
> Có cảm giác code của em run được nhưng khó maintain vì structure khó nhìn. Hơi "junior" chút.
> 
> * Có dòng trống giữa các code block.
> * Đặt tên biến đồng bộ, tránh camelCase, snake_case lẫn lộn

cám ơn anh, em sẽ chú ý hơn.

2024-10-04 02:19 UTC, LCALoi123 commented
Em đã fix comments. anh recheck giúp em nha. cám ơn anh

2024-10-05 14:08 UTC, minhphong306 approved these changes
LGTM

2024-10-05 14:09 UTC, minhphong306 commented
Please resolve conflict. @LCALoi123

2024-10-07 01:59 UTC, closed without merging