add solution 14 and 16
playwrightvn/pw-discovery pull request #13
Opened 2024-09-16 09:27 UTC by LCALoi123

2024-09-16 14:05 UTC, minhphong306 commented on .gitignore
revert file này.

2024-09-16 14:24 UTC, minhphong306 commented on README.md
Revert file này

2024-09-16 14:24 UTC, minhphong306 commented on daily-challenges/2024-09/14/lcaloi.29.spec.ts
> +
Remove các dòng trống không cần thiết

2024-09-16 14:28 UTC, minhphong306 commented on daily-challenges/2024-09/14/lcaloi.29.spec.ts
> +    if (BMI < 18.5) result = 'Gầy'
Các khối ngoặc if dù chỉ có 1 dòng, nên cho vào ngoặc nhọn.
Tìm hiểu thêm về một số software failures khi không dùng ngoặc nhọn nhaa

2024-09-16 14:29 UTC, minhphong306 commented on daily-challenges/2024-09/14/lcaloi.29.spec.ts
> +    await page.locator('#username').clear();
Dòng này thực ra không cần lắm. Nhưng em cẩn thận thế cũng ko sao nha.

2024-09-16 14:30 UTC, minhphong306 commented on daily-challenges/2024-09/16/lcaloi_29.spec.ts
> +        await page.locator('#dob').pressSequentially('02292000', { delay: 200 });
Có thể fill theo format ngày tháng: 2024-09-16 nha.
Như nthế này code sẽ sáng sủa, dễ nhìn hơn.

2024-09-16 14:32 UTC, minhphong306 requested changes
Code hơi lộn xộn. Cần hạn chế các dòng trống không cần thiết.
Tìm hiểu thêm về web-first assertion để code được ổn định hơn.

2024-09-17 06:41 UTC, minhphong306 commented
Xóa các file không liên quan nha em. Cả file upload.png cũng bỏ đi nha. Để locally thôi.

2024-09-17 06:49 UTC, LCALoi123 commented
> Xóa các file không liên quan nha em. Cả file upload.png cũng bỏ đi nha. Để locally thôi.

Em xoá rồi nha anh. anh accept em up bài hôm nay lên vs nha

2024-09-18 00:14 UTC, minhphong306 commented on README.md
Revert changes

2024-09-18 00:14 UTC, minhphong306 commented on daily-challenges/2024-09/16/lcaloi_29.spec.ts
> +
Xoá dòng trống thừa

2024-09-18 00:15 UTC, minhphong306 commented on package-lock.json
revert changes

2024-09-18 00:15 UTC, minhphong306 requested changes
Please revert changes

2024-09-18 00:15 UTC, minhphong306 commented on playwright.config.ts
revert changes

2024-09-18 00:15 UTC, minhphong306 commented on package.json
Revert changes

2024-09-24 00:03 UTC, minhphong306 commented
Chắc để tối anh support em sửa lại PR nha. tách riêng của từng ngày để dễ review và dễ merge hơn.

2024-09-24 08:50 UTC, minhphong306 commented on daily-challenges/2024-09/16/lcaloi_29.spec.ts
> +    const arr_txt: string[] = txtInfo.split("\n");
Lẫn lộn camelCase và snake_case

2024-09-24 08:51 UTC, minhphong306 commented on daily-challenges/2024-09/17/lcaloi_29.spec.ts
> +async function getProdInFo(productId: number, page: Page): Promise<ProdInfo> {
```suggestion
async function getProdInfo(productId: number, page: Page): Promise<ProdInfo> {
```

2024-09-24 08:51 UTC, minhphong306 requested changes
Please fix comments

2024-09-28 08:40 UTC, closed without merging

2024-09-28 08:40 UTC, minhphong306 commented
Tham khảo video Daily #0, hướng dẫn cách contribute để tách nhánh cho từng ngày nha em.
Good work!!!