minvp daily challenges 240917
playwrightvn/pw-discovery pull request #18
Opened 2024-09-17 07:02 UTC by minvp

2024-09-17 10:38 UTC, minvp commented on daily-challenges/2024-09/17/min240917.spec.ts
> +            if(number%i == 0){
updated

2024-09-17 23:42 UTC, minhphong306 commented on daily-challenges/2024-09/17/min240917.spec.ts
> +        for (let i = 0; i <= number - 1; i += 2) {
Có thể tối ưu hơn bằng cách: chạy từ 2 tới căn bậc 2 của number: Math.sqrt(number) 
```suggestion
        for (let i = 2; i <= Math.sqrt(number; i += 2); i++) {
```

2024-09-17 23:45 UTC, minhphong306 commented on daily-challenges/2024-09/17/min240917.spec.ts
> +    await page.locator(`//button[@data-product-id='1']`).click()
Có thể tối ưu hơn bằng cách:
- Khai báo locator product1
- Khi dùng gọi ra thôi
```suggestion
    const product1 = page.locator(`//button[@data-product-id='1']`);
    await product1.click({ clickCount: 2});
```

2024-09-17 23:46 UTC, minhphong306 commented on daily-challenges/2024-09/17/min240917.spec.ts
> +    let actual_qtyP1 = await page.locator("(//td[text()='Product 1']/following-sibling::td)[2]").innerText()
Không sử dụng lộn xộn camelCase và snake_case nha.
Dùng 1 loại case thôi.

2024-09-17 23:47 UTC, minhphong306 requested changes
Please fix comments

2024-09-18 12:25 UTC, minvp commented on daily-challenges/2024-09/17/min240917.spec.ts
> +        for (let i = 0; i <= number - 1; i += 2) {
updated

2024-09-18 12:25 UTC, minvp commented on daily-challenges/2024-09/17/min240917.spec.ts
> +    await page.locator(`//button[@data-product-id='1']`).click()
updated

2024-09-18 12:25 UTC, minvp commented on daily-challenges/2024-09/17/min240917.spec.ts
> +    let actual_qtyP1 = await page.locator("(//td[text()='Product 1']/following-sibling::td)[2]").innerText()
updated

2024-09-18 17:22 UTC, minhphong306 commented on daily-challenges/2024-09/17/min240917.spec.ts
> +    await expect(Number(actualQtyP1)).toEqual(testData.qtyP1)
Nên sử dụng web-first assertion:
```suggestion
    let actualQtyP1 = await .innerText()
    await expect(page.locator("(//td[text()='Product 1']/following-sibling::td)[2]")).toHaveText(`${testData.qtyP1}`);
```

2024-09-18 17:22 UTC, minhphong306 commented on daily-challenges/2024-09/17/min240917.spec.ts
> +    await expect(Number(actualQtyP2)).toEqual(testData.qtyP2)
Expect.toEqual là sync matcher => không cần await ở đầu.

2024-09-18 17:23 UTC, minhphong306 commented on daily-challenges/2024-09/18/min240918.spec.ts
> +    await expect(numberOfTask).toEqual(1)
Sử dụng web-first assertion:

expect(..).toHaveCount(1).

2024-09-18 17:24 UTC, minhphong306 commented on daily-challenges/2024-09/18/min240918.spec.ts
> +    page.on('dialog', dialog => dialog.accept())
Cần đưa page.on() lên trước khi trigger event.
```suggestion
    page.on('dialog', dialog => dialog.accept())
    await page.click(`//button[text()='Delete']`)
```

2024-09-18 17:25 UTC, minhphong306 commented on daily-challenges/2024-09/18/min240918.spec.ts
> +    })
```suggestion
    page.on('dialog', async dialog => {
        await dialog.accept('Xin chào, đây là bài thực hành ngày 18 tháng 9 - phiên bản đã chỉnh sửa')
    })
    await page.click('//button[@onclick="editTask(0)"]')
```

Cần đưa page.on trước khi trigger event.

2024-09-18 17:25 UTC, minhphong306 requested changes
Please fix comments

2024-09-22 15:47 UTC, closed without merging