add solution 20,21,22,23,24/09/2024
playwrightvn/pw-discovery pull request #183
Opened 2024-11-01 07:56 UTC by LCALoi123

2024-11-10 07:33 UTC, minhphong306 requested changes
Looks good to me, but please format code @LCALoi123

2024-11-11 03:09 UTC, LCALoi123 commented
> Looks good to me, but please format code @LCALoi123
Code em format hết rồi mà anh nhỉ? file nào chưa format ah anh @minhphong306

2024-11-11 08:03 UTC, playwrightvietnam commented on daily-challenges/2024-09/20/lcaloi_29.spec.ts
> +import {test, expect, Locator} from "@playwright/test";
VD file này chưa format này.
Nếu format rồi thì sẽ là
```suggestion
import { test, expect, Locator } from "@playwright/test";
```

2024-11-11 08:22 UTC, LCALoi123 commented on daily-challenges/2024-09/20/lcaloi_29.spec.ts
> +import {test, expect, Locator} from "@playwright/test";
> VD file này chưa format này. Nếu format rồi thì sẽ là
à à. okei anh. để em đi từng file format lại

2024-11-12 23:00 UTC, merged