feat: add solution for js excercise and playwright
playwrightvn/pw-discovery pull request #19
Opened 2024-09-17 19:37 UTC by khanh5923

Please help me to review this code for Daily challenge 14 & 16

2024-09-17 23:32 UTC, minhphong306 commented on playwright.config.ts
Remove this change

2024-09-17 23:32 UTC, minhphong306 commented on package-lock.json
Remove this change

2024-09-17 23:32 UTC, minhphong306 commented on daily-challenges/2024-09/17/00-problem.md
Remove this change. You may need sync from fork repo for up-to-date code

2024-09-17 23:33 UTC, minhphong306 commented on daily-challenges/2024-09/16/00-problem.md
Remove this change

2024-09-17 23:33 UTC, minhphong306 commented on daily-challenges/2024-09/14/tunganh222Z.java
Remove this change

2024-09-17 23:34 UTC, minhphong306 commented on daily-challenges/2024-09/14/khanh5923.spec.js
> +    height = Math.pow(height,2)
Cách này không sai. Tuy nhiên với công thức đơn giản là phép nhân thì nên dùng height * height để:
- Dễ nhìn hơn.
- Không phải gọi thêm một hàm nữa (tối ưu hơn).

2024-09-17 23:36 UTC, minhphong306 commented on daily-challenges/2024-09/14/khanh5923.spec.js
> +    if(BMI < 18.5) console.log('Gay')
Đối với vòng lặp hoặc điều kiện, nên có ngoặc {} dù chỉ có một dòng code.
Em có thể tìm hiểu thêm về một số case bị fail khi không dùng ngoặc nha.

2024-09-17 23:37 UTC, minhphong306 commented on daily-challenges/2024-09/14/khanh5923.spec.js
> +    else if(BMI >= 30) console.log("Beo phi")
Sai output. Đọc lại đề bài.

2024-09-17 23:38 UTC, minhphong306 commented on daily-challenges/2024-09/14/khanh5923.spec.js
> +test.only("bai1", async({page})=>{
- Format code.
- Hạn chế dùng test.only vì nó sẽ disable các test khác.

2024-09-17 23:38 UTC, minhphong306 commented on daily-challenges/2024-09/14/khanh5923.spec.js
> +    // await baihoc1.click()
Xoá code không dùng tới.

2024-09-17 23:40 UTC, minhphong306 requested changes
Please fix comments

2024-09-18 19:21 UTC, khanh5923 commented on daily-challenges/2024-09/14/khanh5923.spec.js
> +    height = Math.pow(height,2)
Fixed

2024-09-18 19:22 UTC, khanh5923 commented on daily-challenges/2024-09/14/khanh5923.spec.js
> +    if(BMI < 18.5) console.log('Gay')
Okey anh

2024-09-18 19:22 UTC, khanh5923 commented on daily-challenges/2024-09/14/khanh5923.spec.js
> +    else if(BMI >= 30) console.log("Beo phi")
Fixed

2024-09-18 19:22 UTC, khanh5923 commented on daily-challenges/2024-09/14/khanh5923.spec.js
> +test.only("bai1", async({page})=>{
Vâng anh

2024-09-18 19:22 UTC, khanh5923 commented on daily-challenges/2024-09/14/khanh5923.spec.js
> +    // await baihoc1.click()
Noted

2024-09-18 20:10 UTC, closed without merging