feat: add solution for js and playwright exercise 17 & 18
playwrightvn/pw-discovery pull request #22
Opened 2024-09-18 20:16 UTC by khanh5923

Please help me review the code for daily 17 & 18. Also, I have fixed most of the comments you gave me.

2024-09-19 01:18 UTC, minhphong306 commented on daily-challenges/2024-09/18/khanh5923_18.spec.js
> +        await dialog.accept(testData.update); // Cung cấp giá trị mới cho prompt
Khai thật đi, em có dùng ChatGPT ko :v

2024-09-19 01:18 UTC, minhphong306 commented on daily-challenges/2024-09/18/khanh5923_18.spec.js
> +import {test, expect} from '@playwright/test'
Format code

2024-09-19 01:23 UTC, minhphong306 commented on daily-challenges/2024-09/18/00-problem.md
> +<<<<<<< HEAD
Resolve conflict thiếu này.

2024-09-19 01:23 UTC, minhphong306 commented on playwright.config.ts
> +    // headless: false,
Remove các changes không cần thiết nha.

2024-09-19 01:26 UTC, minhphong306 requested changes
Please fix comments.
You shouldn't close the pull request. Just fix it.

2024-09-19 03:07 UTC, khanh5923 commented on daily-challenges/2024-09/18/khanh5923_18.spec.js
> +        await dialog.accept(testData.update); // Cung cấp giá trị mới cho prompt
Hehe dạ có anh, bạn đồng hành code với em mừ. Mà em hong copy paste mô, em có tìm hiểu rùi test lại từng dòng xem cách thức nó hoạt động như nào nữa ạ.

2024-09-19 03:18 UTC, khanh5923 commented on daily-challenges/2024-09/18/khanh5923_18.spec.js
> +import {test, expect} from '@playwright/test'
Dạ vâng anh

2024-09-20 00:57 UTC, minhphong306 commented on daily-challenges/2024-09/14/khanh5923.spec.js
.spec.ts

2024-09-20 00:57 UTC, minhphong306 requested changes
Please invite me to your repo. I will help you fix the commits.

2024-09-22 15:47 UTC, closed without merging