Min240919
playwrightvn/pw-discovery pull request #24
Opened 2024-09-19 13:26 UTC by minvp

2024-09-19 13:26 UTC, minvp commented
Please help me review it

2024-09-22 11:08 UTC, minhphong306 commented on daily-challenges/2024-09/19/min240919.spec.ts
> +import exp from 'constants'
Import thừa

2024-09-22 11:09 UTC, minhphong306 commented on daily-challenges/2024-09/19/min240919.spec.ts
> +            console.log('Alert content is correct!')
Em dùng expect nha. Tham khảo bài giải ngày 19 trên kênh Youtube nha.

2024-09-22 11:11 UTC, minhphong306 requested changes
Please fix comments

2024-09-22 15:27 UTC, minvp commented on daily-challenges/2024-09/19/min240919.spec.ts
> +            console.log('Alert content is correct!')
updated

2024-09-22 15:27 UTC, minvp commented on daily-challenges/2024-09/19/min240919.spec.ts
> +import exp from 'constants'
updated

2024-09-22 16:01 UTC, closed without merging