Add solution for exercise 22-09
playwrightvn/pw-discovery pull request #38
Opened 2024-09-22 11:47 UTC by ththao27

Nhờ anh/chị review giúp em ạ

2024-09-22 13:05 UTC, minhphong306 commented on daily-challenges/2024-09/22/ththao27.spec.js
Đổi tên file lại: .spec.ts

2024-09-22 13:05 UTC, minhphong306 requested changes
Quite good.
Please fix the comment.

2024-09-22 13:48 UTC, ththao27 commented on daily-challenges/2024-09/22/ththao27.spec.js
này không phải viết bằng js thì .js hả anh?

2024-09-22 15:38 UTC, playwrightvietnam commented on daily-challenges/2024-09/22/ththao27.spec.js
Không phải nha.
Mình viết typescript nên .ts

2024-09-23 08:19 UTC, ththao27 commented on daily-challenges/2024-09/22/ththao27.spec.js
ơ tại em viết bằng js nên .js @@ vậy giờ em đổi lại ạ

2024-09-23 16:28 UTC, minhphong306 commented on daily-challenges/2024-09/22/ththao27.spec.js
Đổi đi nha. Để anh merge vào cho gọn.

2024-09-24 08:48 UTC, merged