min240917
playwrightvn/pw-discovery pull request #41
Opened 2024-09-22 16:08 UTC by minvp

2024-09-22 23:49 UTC, minhphong306 commented on daily-challenges/2024-09/17/min240917.spec.ts
> +//         for (let i = 2; i <= Math.sqrt(number); i += 2) {
Vòng lặp tăng 2 này bị sai rồi. Nó sẽ bỏ qua các số lẻ.

Em test thử với number = 9 sẽ thấy sai.

2024-09-22 23:49 UTC, minhphong306 requested changes
Please fix comments.

2024-09-23 06:06 UTC, minvp commented on daily-challenges/2024-09/17/min240917.spec.ts
> +//         for (let i = 2; i <= Math.sqrt(number); i += 2) {
updated

2024-09-23 07:10 UTC, minhphong306 approved these changes
LGTM

2024-09-23 07:10 UTC, merged