feat: add solution js and playwright for daily 17
playwrightvn/pw-discovery pull request #42
Opened 2024-09-22 16:09 UTC by khanh5923

2024-09-22 23:50 UTC, minhphong306 commented on daily-challenges/2024-09/17/khanh5923_17.spec.js
> +    if(input == 1) return console.log(`${input} khong phai la so nguyen to`)
Luôn sử dụng ngoặc với các câu điều kiện, dù chỉ có 1 mệnh đề.
```suggestion
    if(input == 1) {
        return console.log(`${input} khong phai la so nguyen to`)
    }
```

2024-09-22 23:50 UTC, minhphong306 commented on daily-challenges/2024-09/17/khanh5923_17.spec.js
> +    let Sum = 0
```suggestion
    let sum = 0
```

Biến viết kiểu camelCase

2024-09-22 23:51 UTC, minhphong306 requested changes
Please fix comment

2024-09-24 15:09 UTC, minhphong306 commented
Please re-open & fix comments

2024-09-24 15:09 UTC, closed without merging

2024-09-24 16:20 UTC, khanh5923 commented on daily-challenges/2024-09/17/khanh5923_17.spec.js
> +    let Sum = 0
Oh! noted