min240918
playwrightvn/pw-discovery pull request #43
Opened 2024-09-22 16:11 UTC by minvp

2024-09-22 23:53 UTC, minhphong306 commented on daily-challenges/2024-09/18/min240918.spec.ts
> +    await expect(numberOfTask).toEqual(1)
Em nên sử dụng web-first assertion để code được ổn định hơn:
```suggestion
    await expect(page.locator(`//ul[@id="task-list"]`)).toHaveCount(1)
```

2024-09-22 23:53 UTC, minhphong306 commented on daily-challenges/2024-09/18/min240918.spec.ts
> +    await page.getByRole('button').click()
Thiếu verify todo biến mất

2024-09-22 23:54 UTC, minhphong306 requested changes
Please fix comments.

2024-09-23 06:08 UTC, minvp commented on daily-challenges/2024-09/18/min240918.spec.ts
> +    await expect(numberOfTask).toEqual(1)
updated

2024-09-23 06:14 UTC, minvp commented on daily-challenges/2024-09/18/min240918.spec.ts
> +    await page.getByRole('button').click()
updated

2024-09-23 07:12 UTC, minhphong306 approved these changes
LGTM

2024-09-23 07:12 UTC, merged