min240919
playwrightvn/pw-discovery pull request #44
Opened 2024-09-22 16:13 UTC by minvp

2024-09-22 23:55 UTC, minhphong306 commented on daily-challenges/2024-09/19/min240919.spec.ts
> +    page.on('dialog', async dialog => {
Đưa phần logic handle sự kiện lên trên trước lúc trigger sự kiện.

2024-09-22 23:55 UTC, minhphong306 requested changes
Please fix comment.

2024-09-23 06:16 UTC, minvp commented on daily-challenges/2024-09/19/min240919.spec.ts
> +    page.on('dialog', async dialog => {
updated

2024-09-23 07:13 UTC, minhphong306 approved these changes
LGTM

2024-09-23 07:13 UTC, merged