feat: add solution js and playwright for daily 18
playwrightvn/pw-discovery pull request #45
Opened 2024-09-22 16:13 UTC by khanh5923

2024-09-22 23:56 UTC, minhphong306 commented on daily-challenges/2024-09/18/khanh5923_18.spec.js
> +test('bai4_18', async ({ page }) => {
Cách 1 dòng trống sau import cho thoáng.

2024-09-22 23:56 UTC, minhphong306 commented on daily-challenges/2024-09/18/khanh5923_18.spec.js
> +    const onlyAdd = page.locator(`//ul[@id="task-list"]//li`)
Đặt tên solo quá. Nên đặt tên có chủ đích và ý nghĩa.
```suggestion
    const taskListLocator = page.locator(`//ul[@id="task-list"]//li`)
```

2024-09-22 23:58 UTC, minhphong306 requested changes
Code nên có nhiều dòng trống ở các block khác nhau nhìn cho thoáng. Tham khảo code đáp án nha em.

Tên biến đặt có ý nghĩa hơn.

2024-09-24 15:09 UTC, closed without merging

2024-09-24 16:23 UTC, khanh5923 commented on daily-challenges/2024-09/18/khanh5923_18.spec.js
> +test('bai4_18', async ({ page }) => {
Dạ anh

2024-09-24 16:23 UTC, khanh5923 commented on daily-challenges/2024-09/18/khanh5923_18.spec.js
> +    const onlyAdd = page.locator(`//ul[@id="task-list"]//li`)
Dạ để em khắc phục