Min240922
playwrightvn/pw-discovery pull request #55
Opened 2024-09-24 14:36 UTC by minvp

2024-09-24 14:58 UTC, minhphong306 commented on daily-challenges/2024-09/22/min240922.spec.ts
> +let count = countWords(`Chuỗi có thể chứa các dấu câu như dấu chấm, dấu phẩy, hoặc dấu chấm than, nhưng chỉ tính số từ dựa trên các khoảng trắng ngăn cách`)
Code sai với trường hợp chỉ có dấu cách.

2024-09-24 14:58 UTC, minhphong306 requested changes
Please fix comments

2024-09-24 15:15 UTC, minvp commented on daily-challenges/2024-09/22/min240922.spec.ts
> +}
updated

2024-09-24 15:15 UTC, minvp commented on daily-challenges/2024-09/22/min240922.spec.ts
> +let count = countWords(`Chuỗi có thể chứa các dấu câu như dấu chấm, dấu phẩy, hoặc dấu chấm than, nhưng chỉ tính số từ dựa trên các khoảng trắng ngăn cách`)
Updated

2024-09-25 05:31 UTC, minhphong306 approved these changes
LGTM

2024-09-25 05:31 UTC, merged