feat: add solution JS day 18
playwrightvn/pw-discovery pull request #60
Opened 2024-09-25 20:47 UTC by ntlem

2024-09-27 00:59 UTC, minhphong306 commented on daily-challenges/2024-09/18/ntlem.spec.ts
> +
Xoá dòng trống thừa.

2024-09-27 01:00 UTC, minhphong306 commented on daily-challenges/2024-09/19/ntlem.spec.ts
> +}
Lạc đề. Cần viết các function này vào trong object.

2024-09-27 01:00 UTC, minhphong306 commented on daily-challenges/2024-09/19/ntlem.spec.ts
> +const productList = [];
productList là một object. Xem video hướng dẫn giải trên Udemy.

2024-09-27 01:01 UTC, minhphong306 requested changes
Please fix comments.

2024-09-30 00:44 UTC, minhphong306 commented
Please fix all comments and reopen the PR.

2024-09-30 00:44 UTC, closed without merging

2024-09-30 00:47 UTC, ntlem commented
Got it