feature: add solution js and playwright for daily 20
playwrightvn/pw-discovery pull request #76
Opened 2024-09-27 18:30 UTC by khanh5923

Hi @minhphong306 , 
Giúp em review bài này nhé. Lúc chạy thì nó hong được cái mà em sữa mãi cứ thấy đúng đúng mà chạy cũng hong ra :))))) SOS

2024-09-30 00:46 UTC, minhphong306 commented on daily-challenges/2024-09/20/khanh0509_20.spec.js
> +import {test, expect} from '@playwright/test'
Format code

2024-09-30 00:46 UTC, minhphong306 commented on daily-challenges/2024-09/20/khanh0509_20.spec.js
> +    expect(await clickCount.textContent()).toContain(count)
Dùng web-first assertion.

2024-09-30 00:46 UTC, minhphong306 commented on daily-challenges/2024-09/20/khanh0509_20.spec.js
> +        sigleClick : {
```suggestion
        singleClick : {
```

2024-09-30 00:47 UTC, minhphong306 requested changes
Fix comment nha thanh niên.
Lỗi do thiếu await

2024-10-01 06:36 UTC, closed without merging

2024-10-01 09:37 UTC, khanh5923 commented on daily-challenges/2024-09/20/khanh0509_20.spec.js
> +    checkContent(page, testData.sigleClick.count, testData.sigleClick.type, testData.sigleClick.key)
Dạ anh, để em sửa lại