feat: add solution for day 16-09-2024
playwrightvn/pw-discovery pull request #92
Opened 2024-09-28 10:37 UTC by duyen-nt

2024-09-30 00:53 UTC, minhphong306 commented on daily-challenges/2024-09/16/duyennt.spec.ts
> +  import { test, expect } from '@playwright/test';
Đưa phần code playwright ra khỏi function.

2024-09-30 00:53 UTC, minhphong306 requested changes
Please fix comments.

2024-09-30 12:36 UTC, duyen-nt commented on daily-challenges/2024-09/16/duyennt.spec.ts
> +  import { test, expect } from '@playwright/test';
Em đã fix ạ

2024-10-01 06:35 UTC, minhphong306 approved these changes
LGTM

2024-10-01 06:35 UTC, merged