feat: add solution for day 14-09-2024
playwrightvn/pw-discovery pull request #93
Opened 2024-09-28 10:38 UTC by duyen-nt

2024-09-28 14:32 UTC, minhphong306 commented on daily-challenges/2024-09/14/duyennt.spec.ts
> +    let bmi = (weight / (height * height));
Ngoặc tròn ngoài bị thừa.
```suggestion
    let bmi = weight / (height * height);
```

2024-09-28 14:32 UTC, minhphong306 commented on daily-challenges/2024-09/14/duyennt.spec.ts
> +  import {test, expect} from '@playwright/test'
Format code

2024-09-28 14:33 UTC, minhphong306 requested changes
Please fix comments

2024-09-28 14:38 UTC, duyen-nt commented on daily-challenges/2024-09/14/duyennt.spec.ts
> +  import {test, expect} from '@playwright/test'
```suggestion
  import { test, expect } from '@playwright/test'
```

2024-09-30 00:49 UTC, minhphong306 commented on daily-challenges/2024-09/14/duyennt.spec.ts
> +
Xoá dòng trống thừa

2024-09-30 00:50 UTC, minhphong306 commented on daily-challenges/2024-09/14/duyennt.spec.ts
> +        await expect( page.locator('//tbody/tr[1]/td[2]')).toHaveText(testData.username);
Really good. Sử dụng web-first assertion là đúng rồi.

2024-09-30 12:30 UTC, duyen-nt commented on daily-challenges/2024-09/14/duyennt.spec.ts
> +
Em fix r ạ @minhphong306

2024-10-01 06:35 UTC, minhphong306 approved these changes
Good work!!!
Looks good to me.

2024-10-01 06:35 UTC, merged